# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ffi-libfreenect"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Grunzweig", "Eric Monti"]
  s.date = "2011-12-18"
  s.description = "FFI bindings for the libfreenect OpenKinect library"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/glview.rb",
    "examples/ir_view.rb",
    "examples/record.rb",
    "examples/tilt_led.rb",
    "examples/tilt_nod.rb",
    "examples/video_opengl.rb",
    "examples/video_snapshot.rb",
    "lib/ffi/freenect.rb",
    "lib/freenect.rb",
    "lib/freenect/context.rb",
    "lib/freenect/device.rb",
    "lib/freenect/sync.rb",
    "spec/context_spec.rb",
    "spec/device_spec.rb",
    "spec/freenect_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/jgrunzweig/ffi-libfreenect"
  s.rdoc_options = ["--title", "FFI Freenect", "--main", "README.rdoc", "--line-numbers"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "FFI bindings for the libfreenect OpenKinect library"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, [">= 0.5.0"])
    else
      s.add_dependency(%q<ffi>, [">= 0.5.0"])
    end
  else
    s.add_dependency(%q<ffi>, [">= 0.5.0"])
  end
end

