# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ruby-freenect"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Troy Stribling"]
  s.date = "2012-01-02"
  s.description = "Ruby bindings for the libfreenect Kinect driver"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".gems",
    ".rvmrc",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/depth.rb",
    "examples/ir.rb",
    "examples/kinect.rb",
    "examples/led.rb",
    "examples/tilt.rb",
    "examples/tools.rb",
    "examples/video.rb",
    "freenect4r.gemspec",
    "lib/freenect.rb",
    "lib/freenect/driver.rb",
    "lib/freenect/freenect.rb",
    "ruby-freenect.gemspec"
  ]
  s.homepage = "https://github.com/troystribling/ruby-freenect"
  s.rdoc_options = ["--title", "FFI Freenect", "--main", "README.rdoc", "--line-numbers"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Ruby bindings for the libfreenect Kinect driver"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, [">= 1.0.11"])
    else
      s.add_dependency(%q<ffi>, [">= 1.0.11"])
    end
  else
    s.add_dependency(%q<ffi>, [">= 1.0.11"])
  end
end

